#!/bin/bash
#setup dnsmasq on IP address change
#setup iptables rule for masquerading
if [ "$2" = "up" ];then
	if test -f /etc/ap.conf; then
		. /etc/ap.conf
		if [[ x"$NET_CONNECT" == xtrue ]]; then
			iptables -L -t nat | grep MASQ || iptables -t nat -A POSTROUTING -o $2 -j MASQUERADE
		else
			iptables -t nat -D POSTROUTING -o $2 -j MASQUERADE
		fi
	fi
	/usr/share/cockpit/apsetup/apdnsmasqsetup 2>/dev/null || true
fi
if [ "$2" = "down" ];then
	iptables -t nat -D POSTROUTING -o $2 -j MASQUERADE 2>/dev/null|| true
fi

