#!/bin/bash
echo "Please wait"
#Create or modify NM configuration for the Access Point
export WL_IFACE=`ifconfig -a|grep wl|cut -d ":" -f1`
if ! grep -q "id=ap" /etc/NetworkManager/system-connections/*; then
	nmcli con add type wifi ifname $WL_IFACE con-name ap autoconnect yes ssid $1 ipv4.method manual ipv4.addresses $3/24 wifi-sec.key-mgmt wpa-psk wifi-sec.psk "$2" 802-11-wireless.mode ap
else
	nmcli con modify ap ssid $1 ipv4.addresses $3/24 wifi-sec.psk "$2"
fi
#Set config file permission so only root can read
chmod 600 /etc/ap.conf
#Setting for iptable MASQUERADE
sed -i -e s"@NET_CONNECT=.*@NET_CONNECT=$4@g" /etc/ap.conf
#Copy the NM dispatcher script to set up iptables rule and dnsmasq dhcp server
if [ ! -f /etc/NetworkManager/dispatcher.d/90apnmdispatcher ]; then
	cp /usr/share/cockpit/apsetup/90apnmdispatcher /etc/NetworkManager/dispatcher.d/
fi
#Reload and bring up the Access Point
/usr/bin/nmcli con reload 
/usr/bin/nmcli con up ap 
echo "Setup completed, please reconnect to the access point if needed"
