#!/bin/bash
echo "Please wait"
. /etc/ap.conf
#Create or modify NM configuration for the Access Point
export WL_IFACE=`ifconfig -a|grep wl|cut -d ":" -f1`
if ! grep -q "id=ap" /etc/NetworkManager/system-connections/*; then
	nmcli con add type wifi ifname $WL_IFACE con-name ap autoconnect yes ssid $AP_SSID ipv4.method manual ipv4.addresses $AP_IP/24 wifi-sec.key-mgmt wpa-psk wifi-sec.psk "$AP_PASS" 802-11-wireless.mode ap
else
	nmcli con modify ap ssid $AP_SSID ipv4.addresses $AP_IP/24 wifi-sec.psk "$AP_PASS"
fi
#Set config file
chmod 600 /etc/ap.conf
#Copy the NM dispatcher script to set up iptables rule and dnsmasq dhcp server
if [ ! -f /etc/NetworkManager/dispatcher.d/90apnmdispatcher ]; then
	cp /usr/share/cockpit/apsetup/90apnmdispatcher /etc/NetworkManager/dispatcher.d/
fi
#Reload and bring up the Access Point
/usr/bin/nmcli con reload 
/usr/bin/nmcli con up ap 
echo "Setup completed, please reconnect to the access point if needed"
